apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: pod-restarts
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/caiobegotti/pod-restarts/releases/download/v0.1.0/pod-restarts-amd64-linux.tar.gz
    sha256: "663d7f981b3c01dc13bfc2119b0abd0b5b20c85b4b755f6fec9e8cb8be34f343"
    files:
    - from: "./LICENSE"
      to: "."
    - from: "./pod-restarts-amd64-linux"
      to: "."
    bin: "pod-restarts-amd64-linux"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/caiobegotti/pod-restarts/releases/download/v0.1.0/pod-restarts-amd64-darwin.tar.gz
    sha256: "d314e57e5807afc4669c5a25852a733f1bc3140441bbd397b5666b22b5090617"
    files:
    - from: "./LICENSE"
      to: "."
    - from: "./pod-restarts-amd64-darwin"
      to: "."
    bin: "pod-restarts-amd64-darwin"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/caiobegotti/pod-restarts/releases/download/v0.1.0/pod-restarts-amd64-windows.exe.zip
    sha256: "199481b1a5caffe419cf7d2972f19043655ace20ca79394784636e98693b1540"
    files:
    - from: "./LICENSE"
      to: "."
    - from: "./pod-restarts-amd64-windows.exe"
      to: "."
    bin: "pod-restarts-amd64-windows.exe"
  shortDescription: Summary list of all pods with restarts and their last start time
  homepage: https://github.com/caiobegotti/pod-restarts
  description: |
    Usage
      $ kubectl pod-restarts

    For additional options
      $ kubectl pod-restarts --help
